### PR TITLE
Adding read the docs

### PR DESCRIPTION
**Pull request by MarshMue**

### CODE REVIEW

**Comment by msarahan** [comment]
Do you need me to activate this on RTD at all?

**Comment by msarahan** [comment]
PS: I'm assuming we'll set up the badge in the readme once we know the link?

**Comment by rwbogl** [comment]
@msarahan I'll add the badge when we get the link. Do we already have a RTD account?

**Comment by MarshMue** [comment]
I added it to RTD with my Github ID, unless we'd prefer to do it another way? Haven't set this up before so I don't know best practices!

**Comment by msarahan** [comment]
I'd avoid doing it on your personal github ID - better to have it on the org.  With CI, it is sometimes beneficial to have your own account, because organizational ones can get bogged down across multiple projects.

I'm waiting on RTD to show me gerrymandr projects, and I'll activate it when it does.  I have conda-forge on my account, and their 4000 repos slow things down...

**Comment by msarahan** [comment]
well, maybe not - seems like RTD is not per-user in the same way as github or CIs.

**Comment by MarshMue** [comment]
I'll add gerrymandr has a maintainer on RTD

**Pull request merged**
