### PR TITLE
Score functions and pickled the graph!

### PR DESCRIPTION
**Pull request by maxhully**

### CODE REVIEW

**Comment by msarahan** [comment]
I don't know about networkx's pickle implementation specifically, but in general, pickles are poor for doing much of anything permanent.  They are not guaranteed to be compatible across python versions.  I highly recommend considering one of the other options.

**Comment by maxhully** [comment]
Good to know! The pickle is temporary so that people can play around with the chain this afternoon without needing to load the data by hand. I'll make sure not to use it for anything long-term.

**Comment by msarahan** [comment]
Cool.  As long as everyone is using the same python version, you should be fine.

**Comment by rwbogl** [comment]
Changing the base branch to `sandbox` so we can sort through this PR after playing around this afternoon.

**Pull request merged**
